### PR TITLE
Add binder

### PR DESCRIPTION
**Pull request by michalk8**
This PR adds support for binder. 1 thing remains: the `environment.yml` needs to be populated.
It should contain everything needed to run the `.py` files and `.ipynb`, e.g. TensorFlow, Tangram, etc.
I'd use `squidpy[all]` to handle `esda`, `PyQt` (not sure how that will work on binder).

@giovp since you know better what requirements are needed, could you finish this? In the meantime, I will update CSS/conf.py in the main repo.

### CODE REVIEW

**Comment by giovp** [comment]
Let's do it ok, and thanks a lot @michalk8 for setting it up. I'm still not sold about having it tbh...but let's give it a try

**Comment by michalk8** [comment]
Thanks for filling the reqs. Since both repos are now open, I will start cleaning old artifacts, get the docs up.

**Comment by michalk8** [comment]
Quick question: do we really need PyTorch? Also, if yes, the package should be `torch`.

**Comment by michalk8** [comment]
I've removed PyTorch, because tangram-sc already specifies it.

**Comment by michalk8** [comment]
ping @giovp - awaiting review (maybe also change the merge conditions).

**Review by giovp — APPROVED** [review]

**Comment by michalk8** [comment]
Thanks!

**Pull request merged**
