### PR TITLE
Contributing guide

### PR DESCRIPTION
**Pull request by hspitzer**
Add contributing.rst to Squidpy_notebooks explaining how to write examples and tutorials.

This is a first draft, mainly created by taking various comments from @michalk8 and putting them together in one file.

### CODE REVIEW

**Comment by giovp** [comment]
@hspitzer what do we do with this? We could merge it as is I think, and we build it up as we find more stuff

**Comment by hspitzer** [comment]
I will go though this tomorrow, add missing links and then we can merge.
How can I make GitHub render this as rst? For me readme.rst renders fine but contributing.rst does not.

**Comment by giovp** [comment]
yea it's weird. I honestly don't know. Maybe just a bug?

**Comment by hspitzer** [comment]
@giovp ready for review.

**Review by giovp — APPROVED** [review]

**Pull request merged**
