### PR TITLE
add image container and graph examples/tutorials

### PR DESCRIPTION
**Pull request by hspitzer**
adding & fixing examples / tutorials for images

- z-stacks example
- updated image container example -> extended to tutorial
- MIBI-TOF tutorial (only works with https://github.com/theislab/squidpy/pull/354)
- fixed processing examples
- fixed segmentation examples
- fixed feature extraction examples

I'd also propose to add a new subsection in examples for the ImageContainer examples, to differentiate between sq.im API and ImageContainer methods
Additionally, how about adding a separation between dataset analysis tutorials and Squidpy tutorials (loading spatial data, dealing with z-stacks, etc)?

### CODE REVIEW

**Comment by hspitzer** [comment]
locally, building docs now works, CI will fail, because of dependency on "dev" branch from squidpy. Shall I update the requirements for this PR, or should we just merge @giovp ?

**Comment by hspitzer** [comment]
The only thing that is not working locally is the preview images and hover info of all auto-generated examples + tutorials. Any idea how to fix this / why its not working?

**Comment by giovp** [comment]
> The only thing that is not working locally is the preview images and hover info of all auto-generated examples + tutorials.

not sure sorry, what does it mean hover info? also, is it for all previous images or only some?

> Shall I update the requirements for this PR, or should we just merge @giovp ?

I think it's fine to merge?

**Comment by hspitzer** [comment]
> > The only thing that is not working locally is the preview images and hover info of all auto-generated examples + tutorials.
> 
> not sure sorry, what does it mean hover info? also, is it for all previous images or only some?

with hover info I mean the text that is shown if you hover the mouse over the gallery images. Usually a text is show then. This now only works for the pre-generated external tutorials, not for the autogenerated ones.

**Comment by michalk8** [comment]
> The only thing that is not working locally is the preview images and hover info of all auto-generated examples + tutorials. Any idea how to fix this / why its not working?

Hopefully it can still be fixed by doing the thing mentioned in https://github.com/theislab/squidpy_notebooks/issues/27#issuecomment-774774145.

**Comment by hspitzer** [comment]
> > The only thing that is not working locally is the preview images and hover info of all auto-generated examples + tutorials. Any idea how to fix this / why its not working?
> 
> Hopefully it can still be fixed by doing the thing mentioned in [#27 (comment)](https://github.com/theislab/squidpy_notebooks/issues/27#issuecomment-774774145).

Unfortunately that is not it. I checked, and all rst files have the correct format with the extra line. I looked at the built html files, and `html/auto_examples/index.html` contains the correct images, but `html/examples.html` does not.
I suspect that there is something out of date on my system that that this is not an actual issue.

**Comment by hspitzer** [comment]
@michalk8 I saw that there is a dev branch - should we merge this PR to dev instead of master?

**Comment by giovp** [comment]
@michalk8 we'd be almost ready to merge this and sync it with master, but there is this thumbnail issues that we are not sure.

In the `squidpy_notebooks/docs/build/html/examples.html` file it looks like: 
image

but in the `squidpy_notebooks/docs/build/html/auto_examples/index.html` it's correct
image

it's also correct the hover text.

I honestly don't remember if this was the case also before, and that CI will evenutally render thumbnails correctly. I don't think either of ones changed anything on the docs side so we don't know what could be the issue.

unrelated to that, I will have to update couple of tutorials (today or tomorrow) and then we can merge to master both this and `squidpy` main repo I think. Release then will need to wait another 2 weeks (when we submit revision).

**Comment by michalk8** [comment]
> @michalk8 I saw that there is a dev branch - should we merge this PR to dev instead of master?

Currently, it doesn't make a difference (haven't enabled `dev` main docs yet [some issue when building it], will fix it with new release) but afterwards, yes.

> @michalk8 we'd be almost ready to merge this and sync it with master, but there is this thumbnail issues that we are not sure.

If you run `tox -e shallow-docs`, thumbnails for examples are not created because the examples are not run.
Will run `tox -e docs` after https://github.com/theislab/squidpy/pull/360 is merged.

As for missing hover info, not sure how to fix it - it was always like this. However, hover info when looking from API (e.g. [here](https://squidpy.readthedocs.io/en/latest/api/squidpy.gr.interaction_matrix.html#squidpy.gr.interaction_matrix)) works.

> unrelated to that, I will have to update couple of tutorials (today or tomorrow) and then we can merge to master both this and squidpy main repo I think. Release then will need to wait another 2 weeks (when we submit revision).

Sounds good.

**Comment by michalk8** [comment]
> If you run tox -e shallow-docs, thumbnails for examples are not created because the examples are not run.
Will run tox -e docs after theislab/squidpy#360 is merged.

I stand corrected, `tox -e docs` also doesn't show the images, I suspect [this](https://github.com/theislab/squidpy_notebooks/blob/master/docs/source/conf.py#L157) is the issue (haven't tried fixing it yet).
However, when seeing using these files in final docs, it's fine, see below
squidpy_tutorials

The CellProfiler logo is broken because in the main repo, I do not download yet all images (I have a TODO [here](https://github.com/theislab/squidpy/blob/dev/docs/source/conf.py#L39)).

**Comment by michalk8** [comment]
1 small tip: In `references.bib`, please remove `url = ...` and `eprint = ...` (DOI should be sufficient). The problem is that for `url`, it gets prefixed with `https://arxiv.org` and I haven't found a way to change this (don't like this tbh).

I've also changed the `requirements.txt` to use `dev` (so that we know tests pass), therefore this should be merged to `dev` as well (still need to find a nice way to regen dev docs) and the above comment about `dev` https://github.com/theislab/squidpy_notebooks/pull/64#issuecomment-856093128 should be ignored.

Btw, the tutorials looks really cool!

**Comment by hspitzer** [comment]
> > If you run tox -e shallow-docs, thumbnails for examples are not created because the examples are not run.
> > Will run tox -e docs after [theislab/squidpy#360](https://github.com/theislab/squidpy/pull/360) is merged.
> 
> I stand corrected, `tox -e docs` also doesn't show the images, I suspect [this](https://github.com/theislab/squidpy_notebooks/blob/master/docs/source/conf.py#L157) is the issue (haven't tried fixing it yet).
> However, when seeing using these files in final docs, it's fine, see below
> squidpy_tutorials
> 
> The CellProfiler logo is broken because in the main repo, I do not download yet all images (I have a TODO [here](https://github.com/theislab/squidpy/blob/dev/docs/source/conf.py#L39)).

Ok, this looks great! I'll make a note in the contributing guide that thumbnail images only work in the final docs. Could you remind me again how you generated the final docs? Is it easily possible to do that locally? I think there was something about a token needed -- is that still the case now that everything is public? Am I right in thinking that I could add `dev` here https://github.com/theislab/squidpy/blob/c0220c907577196db5f0dd18ff572648a1450612/docs/source/conf.py#L36 and then it would use the dev branch of squidpy_notebooks? I'm happy to have a quick chat about this as well, as this process of linking the repositories in the docs still seems like magic to me. I wanted to document this a bit for future reference.

**Comment by giovp** [comment]
ok I think we are done from my side re notebooks. Shall we merge ?

**Comment by giovp** [comment]
will fix linting and also the napari tutorial is not updated yet, will do it by this evening

**Comment by michalk8** [comment]
> will fix linting and also the napari tutorial is not updated yet, will do it by this evening

Please also check that everything renders as expected, esp. lists (linting can't catch this since it's still valid RST).

**Comment by giovp** [comment]
ok, the updated tutorials don't have lists etc cause they are external notebooks

**Comment by michalk8** [comment]
> Also, how are the examples.rst and tutorials.rst in the main repo updated? I changed them in Squidpy_notebooks, but of course they are still old in the main repo. Is this a CI thing, or do we do that manually?

Already done in `dev` branch (though the function needs to be slightly refactored to use `git clone`).

> I wanted to document this a bit for future reference.

Good idea, I can do this once it's also working with `dev`.

> Also, how are the examples.rst and tutorials.rst in the main repo updated? I changed them in Squidpy_notebooks, but of course they are still old in the main repo. Is this a CI thing, or do we do that manually?

Yes, they need to also be updated (it doesn't need to be this case, if the file order we get from globbing would be the one we want - alt would be to rename the files to e.g. `001_<old_name>_py` or similar).

**Comment by hspitzer** [comment]
> Yes, they need to also be updated (it doesn't need to be this case, if the file order we get from globbing would be the one we want - alt would be to rename the files to e.g. `001_<old_name>_py` or similar).

Ok, its fine to have this as a manual step as long as its documented somewhere. Now we are mixing exeternal tutorials with rst tutorials in one sections (Napari should be sorted in the "internal" tutorials), so your renaming scheme would not work in this case.

**Comment by michalk8** [comment]
Going to merge this because of https://github.com/theislab/squidpy/pull/365 (want to get stable/latest dev running).
We can then better see if there are any problems. Also now, `tox -e docs` in `squidpy`'s repo will try to get your local notebooks/examples, see the contributing.

**Pull request merged**
